name: aggiorna dati vaccini dettaglio regioni

on:
#  push:
  repository_dispatch:
  schedule:
    - cron:  '7 2 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Utilizza l'action github checkout@v2, per automatizzare il check-out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: crea cartella utente bin, copia dentro l'eseguibile di miller
      run: |-
        mkdir -p ~/bin
        cp bin/mlr ~/bin
        cd ~/bin
        chmod +x mlr
    - name: scarica i dati
      run: |-
        export PATH=$PATH:~/bin
        export PATH=$PATH:~/.local/bin
        cd ./webservices/vaccini/
        chmod +x ./datiRegioni.sh
        ./datiRegioni.sh
    - name: Committa e pusha se ci sono variazioni nei dati
      run: |-
        git config user.name "automatico"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "Vaccini dati regionali: ${timestamp}" || exit 0
        git push
