name: aggiorna dati agenas

on:
#  push:
  repository_dispatch:
  schedule:
    - cron:  '30 21 */1 * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Utilizza l'action github checkout@v2, per automatizzare il check-out
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: crea cartella utente bin, copia dentro l'eseguibile di miller e scrape, installa visidata, installa chrome headless
      run: |-
        sudo apt-get install -y libappindicator1 fonts-liberation
        sudo apt-get -f install
        wget http://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome*.deb
        mkdir -p ~/bin
        cp bin/mlr ~/bin
        cp bin/scrape ~/bin
        cd ~/bin
        chmod +x mlr
        chmod +x scrape
        sudo apt-get install python3-setuptools
        pip3 install wheel
        pip3 install visidata
        pip3 install lxml
        sudo pip install yq
        sudo apt-get install dateutils
        sudo apt-get install dos2unix
        sudo locale-gen it_IT
        sudo locale-gen it_IT.UTF-8
        sudo update-locale
    - name: scarica i dati
      run: |-
        export PATH=$PATH:~/bin
        export PATH=$PATH:~/.local/bin
        cd ./webservices/agenas/
        chmod +x ./agenas.sh
        ./agenas.sh
        chmod +x ./agenas_date.sh
        ./agenas_date.sh
    - name: Committa e pusha se ci sono variazioni nei dati
      run: |-
        git config user.name "automatico"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date --iso-8601=seconds)
        git commit -m "Dati agenas: ${timestamp}" || exit 0
        git push
